=== amintoo/recette-website/recette1.dtd
<!ELEMENT recettes (recette+, auteurs+, Categories+, Sous_Categories+, ingredients+,produits+)>
<!-- liste de recette -->
<!ELEMENT recette (titre, resumé, photo, difficulté, ingredientsRec, temps, description, note, Auteur, nbPersonne)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT resumé (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT difficulté (#PCDATA)>
<!ELEMENT ingredientsRec (ingredientRec+)>
<!ELEMENT ingredientRec (#PCDATA)>
<!ELEMENT temps (preparation, cuisson, repos?)>
<!ELEMENT preparation (#PCDATA)>
<!ELEMENT cuisson (#PCDATA)>
<!ELEMENT repos (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT Auteur (#PCDATA)>
<!ELEMENT nbPersonne (#PCDATA)>

<!-- attribut du recette-->
<!ATTLIST recette
	id_rec CDATA #REQUIRED
	datePubli CDATA #REQUIRED
	categorie CDATA #REQUIRED>

	
<!ATTLIST ingredientRec
	ref CDATA #REQUIRED>
	
<!-- attribut de l'auteur-->	
<!ATTLIST Auteur
	ref_auteur CDATA #REQUIRED>
	
<!ELEMENT auteurs (auteur+)>
<!ELEMENT auteur (nom?,prenom, pays, recette_auteur+, biographie)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT pays (#PCDATA)>
<!ELEMENT recette_auteur (#PCDATA)>
<!ELEMENT biographie (#PCDATA)>
<!ATTLIST auteur
	id_aut CDATA #REQUIRED
	sexe CDATA #REQUIRED
>

<!-- liste categorie -->
<!ELEMENT Categories (Categorie+)>
<!ELEMENT Categorie (Description_Categorie?)>
<!ELEMENT Description_Categorie (#PCDATA)>
<!ATTLIST Categorie
	id_cat CDATA #REQUIRED
	nom CDATA #REQUIRED
>

<!-- liste Sous-Categorie -->

<!ELEMENT Sous_Categories (Sous_Categorie+)>
<!ELEMENT Sous_Categorie (DescriptionSCat, Cat_Ref)>
<!ELEMENT DescriptionSCat (#PCDATA)>
<!ELEMENT Cat_Ref (#PCDATA)>
<!ATTLIST Sous_Categorie
	id_souscat CDATA #REQUIRED
	nom CDATA #REQUIRED
>
<!ATTLIST Cat_Ref
	ref_cat CDATA #REQUIRED
>

<!-- liste des Ingredients -->

<!ELEMENT ingredients (ingredient+)>
<!ELEMENT ingredient (recetteIngredient+, DescriptionIngredient+, apportNutritif?, apportEnergie?, saison?)>
<!ELEMENT recetteIngredient (#PCDATA)>
<!ELEMENT DescriptionIngredient (#PCDATA)>
<!ELEMENT apportNutritif (#PCDATA)>
<!ELEMENT apportEnergie (#PCDATA)>
<!ELEMENT saison (#PCDATA)>
<!ATTLIST ingredient
	id_ing CDATA #REQUIRED
	nom CDATA #REQUIRED
>

<!-- liste des produits -->
<!ELEMENT produits (produit+)>
<!ELEMENT produit (#PCDATA)>
<!ATTLIST produit 
  id_pro CDATA #REQUIRED 
  nom CDATA #REQUIRED>

=== amintoo/recette-website/donnees-recettes/Anciens/Recette1.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE recettes SYSTEM "C:\Users\amin\Desktop\Projet\donnees-recettes\recette1.dtd"><recettes>	<recette id_rec="r2830" datePubli="2011-04-24" categorie="SC1">		<titre>Cake à la tomate farcie</titre>		<resumé>							Cake à la tomate farcie - Recettes de cuisine Ôdélices					</resumé>		<photo>http://www.odelices.com/images/recettes/cake-a-la-tomate-farcie.jpg</photo>		<difficulté>Très facile</difficulté>		<ingredientsRec>			<ingredientRec ref="F120"/>			<ingredientRec ref="L300"/>			<ingredientRec ref="L50"/>			<ingredientRec ref="O12"/>			<ingredientRec ref="H20"/>			<ingredientRec ref="t142"/>			<ingredientRec ref="F10"/>			<ingredientRec ref="t120"/>			<ingredientRec ref="S12"/>			<ingredientRec ref="Po40"/>		</ingredientsRec>		<temps>			<preparation>20min</preparation>			<cuisson>25min</cuisson>			<repos/>		</temps>		<description> 			1. Inciser le fond de chaque tomate et vider les graines à l'aide d'une toute petite cuillère (j'ai fait avec le manche d'une cuillère à moka).Saler l'intérieur de chaque tomate et déposer sur un papier absorbant, elles vont dégorger.2. Beurrer et fariner 6 ramequins. Préchauffer le four à 180°C.3. Faire tiédir le lait 20-30 secondes au micro-onde. Battre l'oeuf en omelette, saler et poivrer puis ajouter la farine, la levure, le lait et l'huile.  Ajouter le fromage râpé.4. Dans un bol mélanger la fêta et le thon égoutté à l'aide d'une fourchette et farcir les tomates avec cette préparation.5. Remplir les moules avec la pâte et déposer une tomate dans chaque en l'enfonçant au deux tiers du moule.6. Cuire entre 20 et 25 minutes.		</description>		<note/>		<Auteur ref_auteur="AUT3"/>		<nbPersonne>6</nbPersonne>	</recette>	<recette id_rec="r3136" datePubli="2012-04-09" categorie="SC1">		<titre>Petits cakes au chèvre frais et myrtilles</titre>		<resumé>							 Petits cakes au chèvre frais et myrtilles - les meilleures recettes de cuisine d'Ôdélices					</resumé>		<photo>http://www.odelices.com/images/recettes/petits-cakes-au-chevre-frais-et-myrtilles.jpg</photo>		<difficulté>Très facile</difficulté>		<ingredientsRec>			<ingredientRec ref="F120"/>			<ingredientRec ref="L50"/>			<ingredientRec ref="O12"/>			<ingredientRec ref="H20"/>			<ingredientRec ref="FC20"/>			<ingredientRec ref="B200"/>			<ingredientRec ref="M110"/>		</ingredientsRec>		<temps>			<preparation>10min</preparation>			<cuisson>17min</cuisson>			<repos/>		</temps>		<description> 			1. Dans un saladier, mélangez la farine, le sel, le bicarbonate, les oeufs, le lait et l'huile.2. Quand la pâte est belle, versez-la dans de petits moules à cake huilés.3. Répartissez sur les cakes de petits morceaux de fromage et les myrtilles.4. Faites cuire 17 minutes à 180°C four ventilé. Piquez un cake à l'aide de la pointe d'un couteau afin de vérifier la cuisson.5. Servez à température ambiante avec une salade croquante.					</description>		<note>5</note>		<Auteur ref_auteur="AUT2"/>		<nbPersonne>6</nbPersonne>	</recette>	<recette id_rec="r4275" datePubli="2015-02-08" categorie="SC2">		<titre>Mozzarella panée</titre>		<resumé>							Pour un soir de semaine, si vous voulez faire une salade express mais épatante, faites de la mozzarella panée ! C'est rapide, facile et très syma !					</resumé>		<photo>http://www.odelices.com/images/recettes/mozzarella_panee.jpg</photo>		<difficulté>Très facile</difficulté>		<ingredientsRec>			<ingredientRec ref="B10"/>			<ingredientRec ref="O12"/>			<ingredientRec ref="F120"/>			<ingredientRec ref="CH12"/>		</ingredientsRec>		<temps>			<preparation>5min</preparation>			<cuisson>5min</cuisson>			<repos/>		</temps>		<description> 			1. Coupez les boules de mozzarella en rondelles.2. Mettez la farine et la chapelure dans deux assiettes. Et battez l'oeuf avec une fourchette dans un bol.3. Faites chauffer une poêle avec de l'huile.4. Faites tremper les rondelles de mozzarella dans la farine, puis dans l'oeuf et enfin dans la chapelure.5. Faites frire dans la poêle quelques minutes de chaque côté. Servez avec une salade verte.					</description>		<note>5</note>		<Auteur ref_auteur="AUT1"/>		<nbPersonne>4</nbPersonne>	</recette>	<recette id_rec="r3289" datePubli="2012-11-22" categorie="SC2">		<titre>Oeuf cocotte aux marrons</titre>		<resumé>		</resumé>		<photo>http://www.odelices.com/images/recettes/oeuf_cocotte_aux_marrons.jpg</photo>		<difficulté>Très facile</difficulté>		<ingredientsRec>			<ingredientRec ref="M9"/>			<ingredientRec ref="O12"/>			<ingredientRec ref="C50"/>			<ingredientRec ref="S12"/>			<ingredientRec ref="Po40"/>		</ingredientsRec>		<temps>			<preparation>5min</preparation>			<cuisson>15min</cuisson>			<repos/>		</temps>		<description> 			1. Hachez grossièrement les marrons cuits. Répartissez-les dans 4 ramequins inviduels.2. Répartissez une cuillère de crème sur les marrons.3. Puis cassez les oeufs et ajoutez-en un dans chaque ramequin, en les posant délicatement pour ne pas casser le jaune. Salez et poivrez.4. Placez les ramequins dans le four préchauffé à 180°C, au bain-marie. Faites cuire 15 min jusqu'à ce que le blanc soit bien pris.5. Servez chaud, avec des mouillettes de pain grillé.					</description>		<note/>		<Auteur ref_auteur="AUT1"/>		<nbPersonne>4</nbPersonne>	</recette>	<recette id_rec="r4315" datePubli="2015-03-12" categorie="SC3">		<titre>Endives farcies au thon</titre>		<resumé>							Une salade « hébergée » dans une feuille d'endive ! Une idée gourmande qui ravira les plus jeunes qui pourront d'ailleurs vous aider à farcir les endives !					</resumé>		<photo>http://www.odelices.com/images/recettes/endives_farcies_au_thon1.jpg</photo>		<difficulté>Très facile</difficulté>		<ingredientsRec>			<ingredientRec ref="e300"/>			<ingredientRec ref="t120"/>			<ingredientRec ref="Co30"/>			<ingredientRec ref="C50"/>			<ingredientRec ref="M80"/>			<ingredientRec ref="CI10"/>			<ingredientRec ref="t142"/>			<ingredientRec ref="S12"/>			<ingredientRec ref="Po40"/>		</ingredientsRec>		<temps>			<preparation>15min</preparation>			<cuisson/>			<repos/>		</temps>		<description> 			1. Lavez les tomates, coupez-les en deux et épépinez-les. Emincez finement la ciboulette.2. Mettez dans le bol du robot le thon, les tomates, les cornichons, la crème fraîche, la moutarde et la ciboulette. Mixez le tout grossièrement pour garder quelques morceaux. Salez légèrement et poivrez éventuellement.3. Passez les endives sous l'eau rapidement et enlevez le cône amer à la base des feuilles. Détachez les feuilles une par une, séchez-les bien.4. Répartissez la farce dans les feuilles et servez bien frais.		</description>		<note/>		<Auteur ref_auteur="AUT1"/>		<nbPersonne>4</nbPersonne>	</recette>	<recette id_rec="r1241" datePubli="2006-06-01" categorie="SC16">		<titre>Moules et frites</titre>		<resumé>								Si vous passez par le nord, prenez le temps de déguster des frites savoureuses dans une baraque à frites et n'oubliez pas de goûter à des moules de là-bas !Recettes extraites du livre Craquez pour la cuisine des chtis !					</resumé>		<photo>http://www.odelices.com/images/recettes/moules-frites.jpg</photo>		<difficulté>Très facile</difficulté>		<ingredientsRec>			<ingredientRec ref="MO7"/>			<ingredientRec ref="oi16"/>			<ingredientRec ref="ech12"/>			<ingredientRec ref="CE5"/>			<ingredientRec ref="BEU1"/>			<ingredientRec ref="pom06"/>			<ingredientRec ref="H20"/>			<ingredientRec ref="S12"/>		</ingredientsRec>		<temps>			<preparation>15min</preparation>			<cuisson>30 min</cuisson>			<repos/>		</temps>		<description> 							Pour les moules						1. Grattez les moules et rincez-les soigneusement.2. Pelez et émincez les échalotes et les oignons. Faites-les revenir sans coloration dans une grande sauteuse ou une cocotte avec le beurre 2 à 3 minutes à feu vif.3. Ajoutez les moules, le bouquet garni et le céleri. Mouillez avec le vin blanc.4. Couvrez et laissez cuire à feu vif jusqu' à ce que les moules s'ouvrent complètement (5 minutes environ)..5. Versez les moules et leur jus dans un plat creux. Servez avec les frites et une bière blonde.							Pour les frites : 1. Épluchez les pommes de terre et coupez-les en larges bâtonnets. Lavez-les et essuyez-les soigneusement dans un torchon propre (pour retirer l'amidon).2. Faites chauffer l'huile de friture à 180°C.3. Plongez les frites et laissez-les cuire 10 à 15 minutes. Remontez-les à la surface et laissez-les s'égoutter quelques minutes.4. replongez les frites dans l'huile bien chaude quelques minutes : elles seront dorées, croustillantes à l'extérieur et moelleuses à l'intérieur. Servez-les aussitôt saupoudrées de sel.					</description>		<note/>		<Auteur ref_auteur="AUT4"/>		<nbPersonne>4</nbPersonne>	</recette>	<recette id_rec="r2101" datePubli="2009-02-09" categorie="SC5">		<titre>Gigot d'agneau au cumin</titre>		<resumé>								Pour la cuisson d'un gigot d'agneau, comptez environ 15 min par livre. Il sera rosé à coeur.					</resumé>		<photo>http://www.odelices.com/images/recettes/gigot-d-agneau-au-cumin.jpg</photo>		<difficulté>Très facile</difficulté>		<ingredientsRec>			<ingredientRec ref="a117"/>			<ingredientRec ref="BEU1"/>			<ingredientRec ref="S12"/>			<ingredientRec ref="Po40"/>		</ingredientsRec>		<temps>			<preparation>5min</preparation>			<cuisson>45 min</cuisson>			<repos/>		</temps>		<description> 						1. Salez et poivrez le gigot d'agneau. Recouvrez-le de graines de cumin et déposez-le dans un plat allant au four.2. Répartissez des noisettes de beurre sur le dessus de la viande et versez un fond d'eau dans le plat (environ 2 cm d'eau).3. Faites cuire 45 min dans le four préchauffé à 180°C.4. Servez avec une salade de pousses d' épinards ou de cresson.					</description>		<note/>		<Auteur ref_auteur="AUT1"/>		<nbPersonne>4</nbPersonne>	</r
